# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  localizaweb:
    image: localizaweb
    build:
      context: .
      dockerfile: Localiza.Web/Dockerfile
    ports:
      - 5046:5046
